//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Index { get; set; }
        public int acctNo { get; set; }
        public Nullable<int> pin { get; set; }
        public Nullable<int> balance { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
    }
}
